"use server";

import { requireUser } from "@/lib/auth/require-user";
import prisma from "@/lib/db";
import { revalidateTag } from "next/cache";

import { dailyReportSchema, DailyReportFormType } from "@/lib/zodSchemas";
import { getDailyReportFormData as getFormData } from "@/data/daily-report/get-daily-report-form-data";

export async function getDailyReportFormData(workspaceId: string) {
    return getFormData(workspaceId);
}

export async function submitDailyReport(values: DailyReportFormType) {
    const user = await requireUser();
    if (!user) throw new Error("Unauthorized");

    const validation = dailyReportSchema.safeParse(values);
    if (!validation.success) {
        throw new Error(validation.error.issues[0].message);
    }

    const { workspaceId, entries } = validation.data;

    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);

    await prisma.$transaction(async (tx: any) => {
        let report = await tx.dailyReport.findUnique({
            where: {
                workspaceId_userId_date: {
                    workspaceId,
                    userId: user.id,
                    date: startOfDay,
                },
            },
        });

        if (!report) {
            report = await tx.dailyReport.create({
                data: {
                    workspaceId,
                    userId: user.id,
                    date: startOfDay,
                    status: "SUBMITTED",
                    submittedAt: new Date(),
                },
            });
        } else {
            if (report.status === "ABSENT") {
                report = await tx.dailyReport.update({
                    where: { id: report.id },
                    data: { status: "SUBMITTED", submittedAt: new Date(), isAutoGenerated: false },
                });
            } else {
                report = await tx.dailyReport.update({
                    where: { id: report.id },
                    data: { submittedAt: new Date() },
                });
            }
        }

        // Map safely
        const finalEntries = entries.map((e) => ({
            reportId: report.id,
            taskId: (e.taskId === "other" || !e.taskId) ? null : e.taskId,
            type: (e.taskId === null || e.taskId === "other" || !e.taskId) ? "OTHER" : "TASK" as "OTHER" | "TASK",
            description: e.description,
        }));

        await tx.dailyReportEntry.createMany({
            data: finalEntries,
        });
    });

    revalidateTag(`daily-report-${user.id}-${startOfDay.toISOString()}`, "layout" as any);
    return { success: true };
}
