import { NextResponse } from "next/server";
import prisma from "@/lib/db";

export async function GET(req: Request) {
    // Optionally secure with a secret if called from external
    const authHeader = req.headers.get("authorization");
    if (process.env.CRON_SECRET && authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);

    try {
        // High performance bulk-insert for missing daily reports
        // No locking contention, operates directly in the database.
        const result = await prisma.$executeRaw`
            INSERT INTO daily_reports (id, "workspaceId", "userId", date, status, "isAutoGenerated", "createdAt", "updatedAt")
            SELECT 
                gen_random_uuid(), 
                wm."workspaceId", 
                wm."userId", 
                ${startOfDay}::date, 
                'ABSENT'::"ReportStatus", 
                true, 
                now(), 
                now()
            FROM "WorkspaceMember" wm
            JOIN "user" u ON u.id = wm."userId"
            WHERE NOT EXISTS (
                SELECT 1 FROM daily_reports dr
                WHERE dr."workspaceId" = wm."workspaceId"
                AND dr."userId" = wm."userId"
                AND dr.date = ${startOfDay}::date
            )
        `;

        return NextResponse.json({ success: true, insertedCount: result });
    } catch (error) {
        console.error("Auto absence job failed:", error);
        return NextResponse.json({ error: "Job Failed" }, { status: 500 });
    }
}
