import prisma from "@tusker/db";
import { revalidateTag } from "../../../lib/cache/next-cache";
import { dailyReportSchema, DailyReportFormType } from "../../../lib/zodSchemas";

/**
 * Daily report submission.
 *
 * The caller supplies the acting user, so this works the same for a
 * cookie-authenticated web request, a bearer-token API call, and the Travis
 * assistant acting on a user's behalf.
 */
export class DailyReportService {
    static async submit(userId: string, values: DailyReportFormType) {
        const validation = dailyReportSchema.safeParse(values);
        if (!validation.success) {
            throw new Error(validation.error.issues[0].message);
        }

        const { workspaceId, entries, date: clientDate } = validation.data;

        // Use UTC midnight for the provided client date
        const startOfDay = clientDate ? new Date(`${clientDate}T00:00:00Z`) : new Date();
        if (!clientDate) startOfDay.setUTCHours(0, 0, 0, 0);

        await prisma.$transaction(async (tx: any) => {
            let report = await tx.dailyReport.findUnique({
                where: {
                    workspaceId_userId_date: {
                        workspaceId,
                        userId,
                        date: startOfDay,
                    },
                },
            });

            if (!report) {
                report = await tx.dailyReport.create({
                    data: {
                        workspaceId,
                        userId,
                        date: startOfDay,
                        status: "SUBMITTED",
                        submittedAt: new Date(),
                    },
                });
            } else if (report.status === "ABSENT") {
                report = await tx.dailyReport.update({
                    where: { id: report.id },
                    data: { status: "SUBMITTED", submittedAt: new Date(), isAutoGenerated: false },
                });
            } else {
                report = await tx.dailyReport.update({
                    where: { id: report.id },
                    data: { submittedAt: new Date() },
                });
            }

            const finalEntries = entries.map((e) => ({
                reportId: report.id,
                taskId: (e.taskId === "other" || !e.taskId) ? null : e.taskId,
                type: (e.taskId === null || e.taskId === "other" || !e.taskId) ? "OTHER" : "TASK" as "OTHER" | "TASK",
                description: e.description,
            }));

            await tx.dailyReportEntry.createMany({ data: finalEntries });
        });

        await revalidateTag(`daily-report-${userId}-${startOfDay.toISOString()}`, "layout" as any);
        return { success: true };
    }
}
