import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import { SubTaskSheetProvider } from "@/contexts/subtask-sheet-context";
import { GlobalSubTaskSheet } from "@/components/global-subtask-sheet";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SubTaskSheetProvider>
            {children}
            <GlobalSubTaskSheet />
            <Toaster closeButton position="top-right" />
          </SubTaskSheetProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
