import { Hono } from "hono";
import prisma from "@/lib/db";

const cron = new Hono();

// Helper to verify CRON_SECRET
const verifyCronSecret = (authHeader: string | undefined) => {
    if (!process.env.CRON_SECRET) return true; // Fail open if no secret set (not recommended but allows local dev)
    return authHeader === `Bearer ${process.env.CRON_SECRET}`;
};

/**
 * Auto-absence Job
 */
cron.get("/auto-absence", async (c) => {
    const authHeader = c.req.header("authorization");
    if (!verifyCronSecret(authHeader)) {
        return c.json({ error: "Unauthorized" }, 401);
    }

    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);

    try {
        const result = await prisma.$executeRaw`
            INSERT INTO daily_reports (id, "workspaceId", "userId", date, status, "isAutoGenerated", "createdAt", "updatedAt")
            SELECT 
                gen_random_uuid(), 
                wm."workspaceId", 
                wm."userId", 
                ${startOfDay}::date, 
                'ABSENT'::"ReportStatus", 
                true, 
                now(), 
                now()
            FROM "WorkspaceMember" wm
            JOIN "user" u ON u.id = wm."userId"
            WHERE NOT EXISTS (
                SELECT 1 FROM daily_reports dr
                WHERE dr."workspaceId" = wm."workspaceId"
                AND dr."userId" = wm."userId"
                AND dr.date = ${startOfDay}::date
            )
        `;

        return c.json({ success: true, insertedCount: result });
    } catch (error) {
        console.error("Auto absence job failed:", error);
        return c.json({ error: "Job Failed" }, 500);
    }
});

/**
 * Keep-Warm Job
 */
cron.get("/keep-warm", async (c) => {
    try {
        const startTime = Date.now();
        await prisma.$queryRaw`SELECT 1`;
        const duration = Date.now() - startTime;

        return c.json({
            status: "ok",
            message: "Database connection kept warm",
            duration: `${duration}ms`,
            timestamp: new Date().toISOString()
        });
    } catch (error) {
        console.error("Keep-warm error:", error);
        return c.json({
            status: "error",
            error: String(error),
            timestamp: new Date().toISOString()
        }, 500);
    }
});

export default cron;
