import { KanbanColumn, KanbanSubTask } from "./types";

// Sample data for testing the Kanban board
export const sampleKanbanData: KanbanColumn[] = [
    {
        id: 'todo',
        title: 'To Do',
        status: 'TO_DO',
        color: 'text-gray-700 dark:text-gray-300',
        bgColor: 'bg-gray-100 dark:bg-gray-800',
        tasks: [
            {
                id: '1',
                name: 'Design new landing page',
                description: 'Create mockups for the new landing page with modern design',
                status: 'TO_DO',
                tag: 'DESIGN',
                assignee: {
                    id: 'user1',
                    name: 'John',
                    surname: 'Doe',
                    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
                },
                startDate: '2024-01-15',
                days: 5,
                commentCount: 3,
                parentTaskName: 'Website Redesign',
            },
            {
                id: '2',
                name: 'Setup development environment',
                description: 'Configure local development environment for the project',
                status: 'TO_DO',
                tag: 'CONTRACTOR',
                assignee: {
                    id: 'user2',
                    name: 'Jane',
                    surname: 'Smith',
                    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
                },
                startDate: '2024-01-16',
                days: 2,
                commentCount: 0,
                parentTaskName: 'Project Setup',
            },
        ],
    },
    {
        id: 'in-progress',
        title: 'In Progress',
        status: 'IN_PROGRESS',
        color: 'text-blue-700 dark:text-blue-300',
        bgColor: 'bg-blue-100 dark:bg-blue-900',
        tasks: [
            {
                id: '3',
                name: 'Implement authentication system',
                description: 'Build login, signup, and password reset functionality',
                status: 'IN_PROGRESS',
                tag: 'CONTRACTOR',
                assignee: {
                    id: 'user3',
                    name: 'Mike',
                    surname: 'Johnson',
                    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
                },
                startDate: '2024-01-10',
                days: 7,
                commentCount: 12,
                parentTaskName: 'User Management',
            },
            {
                id: '4',
                name: 'Create database schema',
                description: 'Design and implement the database structure',
                status: 'IN_PROGRESS',
                tag: 'CONTRACTOR',
                assignee: {
                    id: 'user1',
                    name: 'John',
                    surname: 'Doe',
                    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
                },
                startDate: '2024-01-12',
                days: 4,
                commentCount: 5,
                parentTaskName: 'Database Setup',
            },
        ],
    },
    {
        id: 'blocked',
        title: 'Blocked',
        status: 'BLOCKED',
        color: 'text-red-700 dark:text-red-300',
        bgColor: 'bg-red-100 dark:bg-red-900',
        tasks: [
            {
                id: '5',
                name: 'Integrate payment gateway',
                description: 'Waiting for API credentials from payment provider',
                status: 'BLOCKED',
                tag: 'CONTRACTOR',
                assignee: {
                    id: 'user4',
                    name: 'Sarah',
                    surname: 'Williams',
                    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
                },
                startDate: '2024-01-08',
                days: 3,
                commentCount: 8,
                parentTaskName: 'Payment System',
            },
        ],
    },
    {
        id: 'review',
        title: 'In Review',
        status: 'REVIEW',
        color: 'text-yellow-700 dark:text-yellow-300',
        bgColor: 'bg-yellow-100 dark:bg-yellow-900',
        tasks: [
            {
                id: '6',
                name: 'Update user profile page',
                description: 'Add new fields and improve UI/UX',
                status: 'REVIEW',
                tag: 'DESIGN',
                assignee: {
                    id: 'user2',
                    name: 'Jane',
                    surname: 'Smith',
                    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
                },
                startDate: '2024-01-05',
                days: 6,
                commentCount: 15,
                parentTaskName: 'User Profile',
            },
            {
                id: '7',
                name: 'Optimize database queries',
                description: 'Improve performance of slow queries',
                status: 'REVIEW',
                tag: 'CONTRACTOR',
                assignee: {
                    id: 'user3',
                    name: 'Mike',
                    surname: 'Johnson',
                    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
                },
                startDate: '2024-01-07',
                days: 3,
                commentCount: 4,
                parentTaskName: 'Performance',
            },
        ],
    },
    {
        id: 'completed',
        title: 'Completed',
        status: 'COMPLETED',
        color: 'text-green-700 dark:text-green-300',
        bgColor: 'bg-green-100 dark:bg-green-900',
        tasks: [
            {
                id: '8',
                name: 'Setup CI/CD pipeline',
                description: 'Configure automated testing and deployment',
                status: 'COMPLETED',
                tag: 'CONTRACTOR',
                assignee: {
                    id: 'user1',
                    name: 'John',
                    surname: 'Doe',
                    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
                },
                startDate: '2024-01-01',
                days: 5,
                commentCount: 7,
                parentTaskName: 'DevOps',
            },
            {
                id: '9',
                name: 'Write API documentation',
                description: 'Document all API endpoints with examples',
                status: 'COMPLETED',
                tag: 'CONTRACTOR',
                assignee: {
                    id: 'user4',
                    name: 'Sarah',
                    surname: 'Williams',
                    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
                },
                startDate: '2023-12-28',
                days: 4,
                commentCount: 2,
                parentTaskName: 'Documentation',
            },
        ],
    },
    {
        id: 'canceled',
        title: 'Canceled',
        status: 'CANCELED',
        color: 'text-gray-500 dark:text-gray-400',
        bgColor: 'bg-gray-50 dark:bg-gray-900',
        tasks: [
            {
                id: '10',
                name: 'Implement dark mode toggle',
                description: 'Feature postponed to next sprint',
                status: 'CANCELED',
                tag: 'DESIGN',
                assignee: {
                    id: 'user2',
                    name: 'Jane',
                    surname: 'Smith',
                    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
                },
                startDate: '2024-01-03',
                days: 2,
                commentCount: 1,
                parentTaskName: 'UI Improvements',
            },
        ],
    },
];
